### PR TITLE
Build vecmath using Maven

### PR DESCRIPTION
**Pull request by ctrueden**
This introduces a pom.xml which tells Maven how the project is structured. To avoid a boatload of disruptive renames, we override some of Maven's default settings.

It also removes the Ant build files to avoid maintaining multiple build systems.

### CODE REVIEW

**Comment by ctrueden** [comment]
To test, run `mvn` from the command line and compare the output `jar` file with the one built by the Ant build system.

**Comment by gouessej** [comment]
Excellent job. I'm going to test it in less than 10 hours. Keep up the good work :) It looks a lot better than the previous Ant script.

**Comment by gouessej** [comment]
I confirm that it works flawlessly :)

**Comment by ctrueden** [comment]
:+1: Glad to hear it. I'm working on the PRs for java3d-core and java3d-utils now.

**Comment by gouessej** [comment]
Nice, it's going to be very useful and I hope I'll be able to generate and upload the very first Java documentation of Java3D 1.6 :)

**Comment by ctrueden** [comment]
Regarding the javadoc: Maven's javadoc plugin makes this very easy:
```
mvn javadoc:javadoc
```
We could also do it as part of the main build lifecycle if you want—just let me know your preference.

One thing I haven't done though is linked the two downstream projects (java3d-core and java3d-utils) to the upstream javadoc. So the three javadocs won't crosslink. But we can easily do this as soon as there is a stable URL for each portion of the javadoc. Alternately, we could create a javadoc aggregator project that generates a single set of javadoc for all three combined; [here is an example of how that would work](https://github.com/imagej/imagej-javadoc).

**Comment by gouessej** [comment]
You can look at JogAmp's Ardor3D Continuation as it has supported Maven for several years and its Java documentation is already successfully aggregated.

**Pull request merged**
