### PR TITLE
Relocate package prefix to org.jogamp.vecmath

### PR DESCRIPTION
**Pull request by ctrueden**
Updating the package prefix avoids clashes with old versions of Java 3D. This is especially important on OS X, where Java 3D 1.3 is sometimes present on the java.ext.path, taking precedence over the classpath.

See also [this thread on the JogAmp forum](http://forum.jogamp.org/Java-3D-Use-Maven-to-build-and-publish-Maven-artifacts-tp4035555p4035803.html).

### CODE REVIEW

**Comment by gouessej** [comment]
Sorry, Sven wants us to use the package name "**com**.jogamp" instead of "org.jogamp". Moreover, as you have to move lots of files, why not putting them into the standard location src/main/java instead of src?

**Comment by ctrueden** [comment]
Sure, no problem. I'm on it.

**Comment by gouessej** [comment]
You're right, I accept your changes, ...

**Comment by gouessej** [comment]
I came to the same conclusion when comparing with JogAmp's Ardor3D Continuation.

**Comment by ctrueden** [comment]
Wait... so do you want `com.jogamp`, or `org.jogamp`? I already force pushed vecmath here to use `com.jogamp`. And I was working on java3d-core right now... almost done with that—should I continue?

**Comment by ctrueden** [comment]
Oh never mind, looks like I hadn't force pushed yet. But... I agree that we should conform to the standard Maven conventions. I will update the other two PRs to do that, and file another PR for vecmath.

**Comment by ctrueden** [comment]
Actually, my kids are getting too squirrelly now, so I don't have time to work on this anymore immediately. It seems like you are eager to do it, so I will leave the rest to you, unless you say otherwise.

**Comment by gouessej** [comment]
Sorry. We just have to clean a bit the mess and it should be ok.

**Pull request merged**
